from __future__ import annotations

# System defaults
DEFAULT_USER_ID = "global"
DEFAULT_NODE_TYPE = "generic"
DEFAULT_DOMAIN = "general"

# Core node-type identifiers
NODE_TYPE_LOG = "log"
NODE_TYPE_ENTITY = "entity"
NODE_TYPE_DOCUMENT = "document"

# Embedding task identifiers
EMBEDDING_TASK_RETRIEVAL_DOCUMENT = "RETRIEVAL_DOCUMENT"
EMBEDDING_TASK_RETRIEVAL_QUERY = "RETRIEVAL_QUERY"

# Graph default weights
DEFAULT_ENTITY_WEIGHT = 0.55
DEFAULT_RELATIONSHIP_WEIGHT = 0.8
DEFAULT_LOG_WEIGHT = 0.3
DOCUMENT_NODE_WEIGHT = 1.0
NODE_TYPE_CHUNK = "chunk"
CHUNK_NODE_WEIGHT = 0.4
NODE_TYPE_CORPUS = "corpus"
CORPUS_NODE_WEIGHT = 1.0
LLM_MAX_TOKENS_DOCUMENT_SUMMARY = 512
DOCUMENT_SUMMARY_CHAR_LIMIT = 50_000
DEFAULT_CHUNK_SIZE = 600
CORPUS_LLM_CONCURRENCY = 3

# Traversal and search scoring/decay constants
LOG_NODE_HALF_LIFE_DAYS = 30.0
STRUCTURED_NODE_HALF_LIFE_DAYS = 365.0
EDGE_HALF_LIFE_DAYS = 90.0
TRAVERSAL_SIMILARITY_WEIGHT = 0.7
TRAVERSAL_OBSERVATION_WEIGHT = 0.3

# LLM max token limits
LLM_MAX_TOKENS_CONSOLIDATION = 1024
LLM_MAX_TOKENS_RELATIONSHIP_SUPERSEDES = 64
LLM_MAX_TOKENS_EXTRACTION = 32768
LLM_MAX_TOKENS_FACT_COLLISION = 64
LLM_MAX_TOKENS_GRAPH_SUMMARY_DRAFT = 2048
LLM_MAX_TOKENS_GRAPH_SUMMARY_THOUGHT = 512
LLM_MAX_TOKENS_GRAPH_SUMMARY_FINAL = 2048
LLM_MAX_TOKENS_PREDICATE_RESOLUTION = 256

# Firestore/query limits and batching
CONSOLIDATION_LOG_QUERY_LIMIT = 50
RELATIONSHIP_SUPERSEDE_CANDIDATE_LIMIT = 10
TRAVERSE_NEIGHBOR_QUERY_LIMIT = 50
TRAVERSE_BATCH_SIZE = 100

# Source log enrichment limits
SOURCE_LOGS_MAX_PER_NODE = 2
SOURCE_LOGS_MAX_TOTAL = 30
SOURCE_LOG_SNIPPET_LENGTH = 250
